cask_args appdir: "/Applications"
tap "homebrew/cask-cask"
tap "telemachus/brew", "https://telemachus@bitbucket.org/telemachus/brew.git"

# Packages
brew "ack"
brew "anyenv"
brew "autoconf"
brew "automake"
brew "boot2docker"
brew "bsdmake"
brew "cgdb"
brew "chromedriver"
brew "ctags"
brew "cmake"
brew "colordiff"
brew "docker"
brew "figlet"
brew "fontforge"
brew "gd"
brew "gettext"
brew "ghq"
brew "gist"
brew "git"
brew "go"
brew "hub"
brew "imagemagick"
brew "jpeg"
brew "jq"
brew "lv"
brew "nkf"
brew "node"
brew "openssl"
brew "peco"
brew "rbenv"
brew "reattach-to-user-namespace"
brew "ruby-build"
brew "the_silver_searcher"
brew "tig"
brew "tmux"
brew "tree"
brew "vim", args: ["with-ruby", "with-lua"]
brew "wget"
brew "z"
brew "zsh"

# .dmg
cask "xquartz" # required reboot to xquartz enable
cask "meld"
cask "alfred"
cask "appcleaner"
cask "bettertouchtool"
cask "clipy"
cask "coteditor"
cask "dash"
cask "dropbox"
cask "evernote"
cask "gitify"
cask "google-chrome"
cask "google-japanese-ime"
cask "gyazo"
cask "keepassx"
cask "kindle"
cask "macvim"
cask "sequel-pro"
cask "simpholders"
cask "skitch"
cask "skype"
cask "sourcetree"
cask "trailer"
cask "vagrant"
cask "virtualbox"
cask "iterm2"

mas "LINE", id: 539883307
mas "FuzzyTime", id: 950297058
